version: 2

project_name: symbol

builds:
  - id: symbol
    main: ./cmd/symbol
    binary: symbol
    ldflags:
      - -s -w -X github.com/symbolsecurity/cli/internal/version.Version={{.Version}} -X github.com/symbolsecurity/cli/internal/version.Commit={{.ShortCommit}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc

release:
  draft: true
